lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
    url(r'^new$', views.new_list, name='new_list'),
]

superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from lists import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/', include('lists.urls')),
    # url(r'^admin/', admin.site.urls),
]

lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import render, redirect
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html')


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'list.html', {'list': list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('/lists/%d/' % (list_.id,))

lists/templates/home.html
<html>
    <head>
        <title>To-Do List</title>
    </head>
    <body>
        <h1>Start a new To-Do list</h1>
        <form action="/lists/new" method="POST">
        {% csrf_token %}
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
        </form>
    </body>
</html>

lists/templates/list.html
<html>
    <head>
        <title>To-Do List</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form action="/lists/{{ list.id }}/add_item" method="POST">
        {% csrf_token %}
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
        </form>
        <table id="id_list_table">
            <tr>
                {% for item in list.item_set.all %}
                    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
                {% endfor %}
            </tr>
        </table>
    </body>
</html>